apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
       k8s-app: {{ .Values.name }} 
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.kibana_image }}:{{ .Values.image_tag }}"
        command:
        - /bin/bash
        - -c
        - '/usr/share/kibana/bin/kibana-plugin remove x-pack && /usr/local/bin/kibana-docker'        
        imagePullPolicy: {{ .Values.pull_policy }}        
        ports:
        - containerPort: {{ .Values.internal_port }}
          name: ui
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: "config"
        configMap:
          name: kibana-config
