apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: {{ .Values.name }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.external_port }}
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: {{ .Values.name }}
